server:
  port: 9001
spring:
  application:
    name: ihrm-system
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.56.2:3306/ihrm?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 12345678
mybatis-plus:
  mapper-locations: classpath*:/Mapper/system/**/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 注册服务
eureka:
  client:
    # Eureka客户端与Eureka服务端进行交互的地址
    service-url:
      defaultZone: http://192.168.56.2:10000/eureka/