# build  docker-compose.yml
version: '3'
services:
  ihrm-eureka:
    build:
      context: ./ihrm-eureka
    restart: always
    container_name: ihrm-eureka
    # 镜像名
    image: ihrm-eureka
    ports:
      - 6060:6060
    volumes:
      - "./logs:/ihrm-eureka/logs"