server:
  port: 9003
spring:
  application:
    ## 应用名称
    name: ihrm-employee
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.56.2:3306/ihrm?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 12345678
mybatis-plus:
  mapper-locations: classpath*:/Mapper/employee/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl